### ISSUE TITLE
Fails to build on OpenBSD

### ISSUE THREAD

**Issue by werdl** [savonet/ocaml-mem_usage#9]
### Description

Liquidsoap fails to build on OpenBSD 7.7, giving the following error:
```
#=== ERROR while compiling mem_usage.0.1.2 ====================================#
# context     2.3.0 | openbsd/x86_64 | ocaml-base-compiler.5.4.0 | https://opam.ocaml.org#5bf570252bd9fee71938b828ca0b86573c1e3355
# path        ~/.opam/5.4.0/.opam-switch/build/mem_usage.0.1.2
# command     ~/.opam/5.4.0/bin/dune build -p mem_usage -j 1 @install
# exit-code   1
# env-file    ~/.opam/log/mem_usage-61193-53e8b2.env
# output-file ~/.opam/log/mem_usage-61193-53e8b2.out
### output ###
# File "lib/dune", line 7, characters 9-18:
# 7 |   (names mem_usage)
#              ^^^^^^^^^
# (cd _build/default/lib && /usr/bin/cc -O2 -fno-strict-aliasing -fwrapv -fPIC -pthread -D_FILE_OFFSET_BITS=64 -O2 -fno-strict-aliasing -fwrapv -fPIC -pthread -g -I /home/werdl/.opam/5.4.0/lib/ocaml -o mem_usage.o -c mem_usage.c)
# mem_usage.c:204:10: fatal error: 'sys/sysinfo.h' file not found
# #include <sys/sysinfo.h>
#          ^~~~~~~
# 1 error generated.
```
`sysinfo.h` is a Linux-only library. Is this going to be fixed?

### Steps to reproduce

Follow the opam build instructions on OpenBSD 7.7.

### Expected behavior

Successful build.

### Log extracts

```
#=== ERROR while compiling mem_usage.0.1.2 ====================================#
# context     2.3.0 | openbsd/x86_64 | ocaml-base-compiler.5.4.0 | https://opam.ocaml.org#5bf570252bd9fee71938b828ca0b86573c1e3355
# path        ~/.opam/5.4.0/.opam-switch/build/mem_usage.0.1.2
# command     ~/.opam/5.4.0/bin/dune build -p mem_usage -j 1 @install
# exit-code   1
# env-file    ~/.opam/log/mem_usage-61193-53e8b2.env
# output-file ~/.opam/log/mem_usage-61193-53e8b2.out
### output ###
# File "lib/dune", line 7, characters 9-18:
# 7 |   (names mem_usage)
#              ^^^^^^^^^
# (cd _build/default/lib && /usr/bin/cc -O2 -fno-strict-aliasing -fwrapv -fPIC -pthread -D_FILE_OFFSET_BITS=64 -O2 -fno-strict-aliasing -fwrapv -fPIC -pthread -g -I /home/werdl/.opam/5.4.0/lib/ocaml -o mem_usage.o -c mem_usage.c)
# mem_usage.c:204:10: fatal error: 'sys/sysinfo.h' file not found
# #include <sys/sysinfo.h>
#          ^~~~~~~
# 1 error generated.
```

### Script extracts

N/A

### Liquidsoap version

```text
Attempting to install 2.4.1.
```

### Liquidsoap build config

```text
N/A
```

### Installation method

From OPAM

**Comment by toots** [comment]
Thanks for reporting. `mem_usage` won't build on BSD systems indeed. Let me see what I can do. Are you a BSD developer?

**Comment by toots** [comment]
Ho @werdl. The modules does build on freeBSD and is using this library: https://github.com/bsdimp/libsysinfo

Are you able to check if this code can be ported to openbsd?

**Comment by werdl** [comment]
Hi, I'm not a BSD developer lol, I'm just a high school student. 

It looks as if the library you mentioned could be ported, with the caveat that the kernel swap availability implementation would have to be patched or removed (as OpenBSD does not offer the functions used afaik). Additionally, in order to use `sysctlbyname`, [https://github.com/ibara/sysctlbyname](https://github.com/ibara/sysctlbyname) would have to be used as OpenBSD does not provide this function out of the box. Other than those relatively minor patches, it looks as if building libsysinfo would be possible. Lmk if there is anything further I can do to assist!

**Comment by toots** [comment]
Ha ok!

I don't really have access to an openbsd box.

I'm not sure how to best proceed.

From this module's perspective, I can try and mark it as incompatible with openbsd but I don't think that this is an ideal solution for you.

Liquidsoap used to be able to compile without `mem_usage` so it could be possible to do that again but, considering that windows, macos, linux and freebsd are supported it'd be sad to have to do it.

Last option would be to work with the openbsd people and try to adapt this code and make it a package available there.

What do you think?

BTW I'm also happy to help if given access to a openbsd box..

**Comment by werdl** [comment]
Ok, so I think the best way to approach this would be to write a package similar to `conf-sysinfo`, but for OpenBSD. A similar interface (header and shared object) could be built and installed, then much like `conf-sysinfo` could be added as a dependency here for OpenBSD. I think that from the perspective of this package, no change would be required (as the kernel swap function I patched out doesn't pertain to this package).

I would happy to deal with the business of properly patching and writing an installation `Makefile` for an OpenBSD version of `libsysinfo`. 
The way that `conf-sysinfo` seems to work, based on poking around in the `opam` package repo, is that it only installs IF `libsysinfo` (a FreeBSD port) is already installed. The new package would work in a similar way, albeit that rather than installing a port the user would have to install it manually. Would you be able to help me publish a package with these requirements at some point (I have no experience with OCaml)?

I think this is the best solution requiring the least amount of changed code.

Thanks so much for your prompt responses!

**Comment by toots** [comment]
Yes, that sounds like a plan!

`conf-sysinfo` itself is jut a configuration package used to tell `opam` what system packages are required. 

If you look at [its source](https://github.com/ocaml/opam-repository/blob/master/packages/conf-sysinfo/conf-sysinfo.1/opam) you'll see that it only lists one dependency for `freebsd`.

The reason it behaves like you are seeing right now is because no external dependency for `openbsd` are defined in the package. Therefore, `opam` thinks that you don't need anything to get the functionality (just like it would be on linux) and directly proceeds with building `mem_usage`, which fails.

Once you have a locally ported `libsysinfo`, you should be able to confirm that it works by compiling `mem_usage` via `opam`.

Then if you make it an `openbsd` package that other people can install, all you'd have to do is list it the package there and `opam` would install it when needed!

**Comment by toots** [comment]
Sorry we would also have to add `openbsd` in the available section there and also here: https://github.com/ocaml/opam-repository/blob/master/packages/mem_usage/mem_usage.0.1.2/opam#L25

**Comment by werdl** [comment]
I am kind of busy with school right now, but should be able to write the patch in a couple of weeks.
